title = "ZxSlug's Portfolio"

[background]
enabled = true
filename = "comms-background.png"


[met]
enabled = false
text = "Moldova"


[description]
enabled = true
text = """
    I only do commissions
    prices can be discussed in dms
    Click the discord button to get sent to my portfolio server
    <a class="hoverable" href="javascript://undefined" onclick='loadVideo(`sfx_showcase.mov`)'>Video Link</a> <a class='hoverable' href='../videos/sfx_showcase.mov'>(alt)</a>
    """


[social]
enabled = true

[social.discord]
enabled = true
url = "https://discord.gg/7dvac795Ph"
icon_path = "svg/socials/discord_logo.svg"


[resources]
enabled=true

[resources.pfp]
enabled = false
filename = "pfp.jpg" # The image needs to be stored in the images folder.

[resources.sprites]
enabled = false
filename = "" # The gif needs to be stored in the images folder.
