title = "Slug's SFX thing"

[background]
enabled = true
filename = "sfx_bg.png"

[met]
enabled = false
text = ""

[description]
enabled = true
text = """
    i do SFX too
    you can check out stuff in the link below (the animation is NOT mine)
    <a class="hoverable" href="javascript://undefined" onclick='loadVideo(`sfx_showcase.mov`)'>Video Link</a> <a class='hoverable' href='../videos/sfx_showcase.mov'>(backup)</a>
"""

[social]
enabled = false

[social.discord]
enabled = true
url = "https://discord.com/users/1010989813874311199"
icon_path = "svg/socials/discord_logo.svg"

[social.twitter]
enabled = true
url = "https://twitter.com/SlugWav"
icon_path = "svg/socials/twitter_logo.svg"

[resources]
enabled = true

[resources.pfp]
enabled = false
filename = ""

[resources.sprites]
enabled = false
filename = ""